title: Agartica Gallery
email: agarticaedits@gmail.com
description: >-
  The cool and amazing gallery of Agartica.
baseurl: ""
url: "https://agartica.github.io"
twitter_username: Juno_Edits
github_username: agartica

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
